version: '3'
services:
  db:
    container_name: db_dev
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    env_file:
      - ./.env/.env.dev
    ports:
      - '5432:5432'
    volumes:
      - db-dev:/var/lib/postgresql/data

volumes:
  db-dev:
