version: '3'
services:
  api:
    container_name: api_dev
    build:
      context: .
      dockerfile: ./docker/node.Dockerfile
      target: dev
    volumes:
      - type: bind
        source: '.'
        target: '/app'
    depends_on:
      - db
    env_file:
      - ./.env/.env.dev
    ports:
      - '3000:3000'
    networks:
      - transcendence-network

  db:
    container_name: db_dev
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    env_file:
      - ./.env/.env.dev
    ports:
      - '5432:5432'
    volumes:
      - db-dev:/var/lib/postgresql/data
    networks:
      - transcendence-network

volumes:
  db-dev:

networks:
  transcendence-network:
    driver: bridge
