name: Backend CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Start Docker Compose
        run: docker-compose -f backend/docker-compose.ci.yaml up -d

      - name: Follow logs
        run: docker-compose -f backend/docker-compose.ci.yaml logs -f api

      - name: Stop Docker Compose
        run: docker-compose -f backend/docker-compose.ci.yaml down
