name: Backend test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Start Docker Compose
        run: docker-compose -f backend/docker-compose.test.yaml up -d

      - name: Follow logs
        run: docker-compose -f backend/docker-compose.test.yaml logs -f api

      - name: Check container status
        run: |
          status=$(docker inspect api_test --format='{{.State.ExitCode}}')
          if [ "$status" -ne "0" ]; then
            exit $status
          fi

      - name: Stop Docker Compose
        run: docker-compose -f backend/docker-compose.test.yaml down
