name: Frontend test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: npm install
        run: cd frontend && npm install

      - name: npm run build
        run: cd frontend && npm run build

      - name: npm run test
        run: cd frontend && npm run test
